wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.10
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1695370984.426761
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      - 105
      3:
      - 7
      - 23
      4: 3.11.5
      5: 0.15.10
      8:
      - 2
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
