in_debug : True
hyperparameters:
 learning_rate : 3e-4
 batch_size : 4
dataset_params:
  data_dir : "/home/frederik/UncertainDepths/data/external/KITTI/"
  num_workers: 2
  min_depth : 1e-3
  max_depth : 80
  input_height: 352
  input_width: 704
trainer_args:
  max_epochs: 20 
