in_debug : True
pdb_disabled: False
save_images: False
loss_function: "MSELoss"
seed: 442
eval_garg_crop: True
eval_eigen_crop: False
neural_net_param_multiplication_factor: 64
save_images_path: "/home/jbv415/UncertainDepths/src/models/outputs/"
hyperparameters:
 learning_rate : 3e-4
 batch_size : 8 
dataset_params:
  data_dir : "/home/jbv415/UncertainDepths/data/external/KITTI/"
  num_workers: 8
  min_depth : 1e-8
  max_depth : 80
  input_height: 352
  input_width: 704
trainer_args:
  max_epochs: 80
defaults: 
 - models: stochastic_unet
 - _self_
