in_debug : True
pdb_disabled: False
save_images: False
loss_function: "MSELoss"
seed: 442
slurm_id: 1
eval_garg_crop: True
eval_eigen_crop: False
neural_net_param_multiplication_factor: 96
save_images_path: "/home/jbv415/UncertainDepths/src/models/outputs/"
results_df_prefix: "test_"
transforms:
 rand_crop: False
 kb_crop: True
 rotate: True
 flip_LR: True
 rand_aug: True
 rotational_degree: 2.0 
hyperparameters:
 learning_rate: 3e-4
 batch_size: 8
trainer_args:
  max_epochs: 50
OOD:
  use_white_noise_box_test: True
defaults: 
 - models: Posthoc_Laplace
 - dataset_params: KITTI
 - _self_
